name = "bandit"
description = "Runs the Bandit static analysis tool on the project."
command = "/home/matt/PycharmProjects/matt_raio_bot_constraints/venv/bin/python -c \"import asyncio; from slash_commands import run_bandit; asyncio.run(run_bandit())\""