name = "quizme"
description = "Starts an interactive quiz on CCNP ENCOR topics."
command = "/home/matt/PycharmProjects/CCNP_Trainer/venv/bin/python -c \"import asyncio; from slash_commands import quizme; asyncio.run(quizme())\""
